// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "operator/pkg/clientset/typed/myweb/v1"

	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeOperatorV1 struct {
	*testing.Fake
}

func (c *FakeOperatorV1) MyWebs(namespace string) v1.MyWebInterface {
	return &FakeMyWebs{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeOperatorV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
